{{- if .Values.capi.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kamaji-control-plane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capx-system
{{- end }}
