{{- if and .Values.capi.enabled .Values.capi.readinessJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-capi-cert
  namespace: capi-operator-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: wait
        image: busybox
        command: ["/bin/sh", "-c", "for i in $(seq 1 60); do if kubectl get secret {{ .Values.capi.certSecretName }}; then exit 0; fi; sleep 5; done; exit 1"]
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: {{ .Values.capi.readinessJob.timeoutSeconds }}
{{- end }}
