{{- if .Values.metallb.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.metallb.namespace }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{- end }}
