{{- if and .Values.metallb.enabled .Values.metallb.addressPool.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.addressPool.name }}
  namespace: {{ .Values.metallb.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  addresses:
    {{- toYaml .Values.metallb.addressPool.addresses | nindent 4 }}
{{- end }}

{{- if and .Values.metallb.enabled .Values.metallb.l2Advertisement.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.metallb.l2Advertisement.name }}
  namespace: {{ .Values.metallb.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ipAddressPools:
    - {{ .Values.metallb.addressPool.name }}
{{- end }}
